language: java
before_install:
    - "sudo apt-get purge openjdk*"
    - "sudo apt-get remove oracle-java7-installer"
    - "sudo apt-get clean"
    - "sudo apt-get autoremove"
    - "sudo add-apt-repository -y ppa:webupd8team/java"
    - "sudo apt-get update"
install:
    - "sudo apt-get install oracle-java8-installer"
    - "sudo update-java-alternatives -s java-8-oracle"
    - "java -version"
    - "javac -version"
after_failure:
    - "mvn test -e"
    - "java -version"
    - "javac -version"
