language: java
before_install:
    - "sudo apt-get purge openjdk*"
    - "sudo add-apt-repository -y ppa:webupd8team/java"
    - "sudo apt-get update"
install:
    - "sudo apt-get install oracle-java8-set-default"
before_script:
    - "java -version"
    - "javac -version"
    - "sudo update-java-alternatives -s java-8-oracle"
    - "java -version"
    - "javac -version"
